name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  TF_VERSION: '1.12.1'        # Updated to latest stable
  TFLINT_VERSION: '0.58.1'    # Updated to latest stable
  TFSEC_VERSION: '1.28.14'    # Updated to latest stable

jobs:
  lint-and-scan:
    name: Lint & Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Cache Terraform plugins
        uses: actions/cache@v4
        with:
          path: |
            .terraform
            ~/.terraform.d/plugin-cache
          key: ${{ runner.os }}-terraform-${{ env.TF_VERSION }}-${{ hashFiles('**/.terraform.lock.hcl') }}

      - name: Install TFLint
        run: |
          curl -sLo tflint.zip \
            https://github.com/terraform-linters/tflint/releases/download/v${{ env.TFLINT_VERSION }}/tflint_linux_amd64.zip
          unzip tflint.zip -d /usr/local/bin/
          tflint --version

      - name: Install tfsec
        run: |
          curl -sLo tfsec \
            https://github.com/aquasecurity/tfsec/releases/download/v${{ env.TFSEC_VERSION }}/tfsec-linux-amd64
          chmod +x tfsec
          mv tfsec /usr/local/bin/
          tfsec --version

      - name: Terraform Init
        run: terraform init
        working-directory: ./

      - name: Format Check
        run: terraform fmt -check -recursive
        working-directory: ./

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./

      - name: TFLint Scan
        run: |
          tflint --init
          tflint
        working-directory: ./

      - name: tfsec Security Scan
        run: tfsec .
        working-directory: ./

  plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: lint-and-scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ./

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: tfplan

  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: ./

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ./